export type FactorVector = { value: number; momentum: number; quality: number; volatility: number; composite: number };
export type RiskMetrics = { volatility: number; var95: number; cvar95: number; beta: number; maxDrawdown: number; sharpe: number | null; riskPerTrade: number; positionSize: number };
export type OptionLeg = { type: "call" | "put"; side: "buy" | "sell"; strike: number; premium: number; quantity: number };
const mean=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0; const sd=(a:number[])=>{if(a.length<2)return 0;const m=mean(a);return Math.sqrt(mean(a.map(x=>(x-m)**2)))};
export function returns(closes:number[]){return closes.slice(1).map((x,i)=>closes[i]?x/closes[i]-1:0).filter(Number.isFinite)}
export function maxDrawdown(closes:number[]){let peak=0,dd=0;for(const p of closes){peak=Math.max(peak,p);if(peak)dd=Math.min(dd,p/peak-1)}return Math.abs(dd)*100}
export function riskMetrics(closes:number[],capital:number,riskPct:number,stopDistance:number):RiskMetrics{const r=returns(closes),vol=sd(r)*Math.sqrt(252)*100,m=mean(r),s=sd(r),sharpe=s?m/s*Math.sqrt(252):null,sorted=[...r].sort((a,b)=>a-b),idx=Math.max(0,Math.floor(sorted.length*.05)),var95=Math.abs((sorted[idx]??0)*100),tail=sorted.slice(0,idx+1),cvar95=Math.abs(mean(tail)*100),riskCapital=capital*riskPct/100;return{volatility:vol,var95,cvar95,beta:1,maxDrawdown:maxDrawdown(closes),sharpe,riskPerTrade:riskCapital,positionSize:stopDistance>0?Math.floor(riskCapital/stopDistance):0}}
export function factorScore(closes:number[],volumes:number[]=[]):FactorVector{const r=returns(closes),n=closes.length,last=closes[n-1]??0,ma=(k:number)=>mean(closes.slice(-Math.min(k,n))),value=50,momentum=Math.max(0,Math.min(100,50+(last/Math.max(ma(50),.0001)-1)*500)),quality=Math.max(0,Math.min(100,50+mean(r.slice(-20))*10000)),volatility=Math.max(0,Math.min(100,100-sd(r)*Math.sqrt(252)*500)),composite=value*.2+momentum*.35+quality*.2+volatility*.25;return{value,momentum,quality,volatility,composite}}
export function monteCarlo(closes:number[],paths=1000,horizon=30){const r=returns(closes),mu=mean(r),sigma=sd(r),out:number[]=[];for(let p=0;p<paths;p++){let v=closes[closes.length-1]??0;for(let i=0;i<horizon;i++){const u=Math.random()||1e-9,z=Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*Math.random());v*=Math.max(.01,1+mu+sigma*z)}out.push(v)}out.sort((a,b)=>a-b);return{p05:out[Math.floor(paths*.05)]??0,p50:out[Math.floor(paths*.5)]??0,p95:out[Math.floor(paths*.95)]??0}}
const erf=(x:number)=>{const s=x<0?-1:1,a=Math.abs(x),t=1/(1+.3275911*a),p=((((1.061405429*t-1.453152027)*t+1.421413741)*t-.284496736)*t+.254829592)*t;return s*(1-p*Math.exp(-a*a))};const cdf=(x:number)=>.5*(1+erf(x/Math.SQRT2));
export function blackScholes(type:"call"|"put",spot:number,strike:number,tYears:number,rate:number,vol:number){const v=Math.max(vol,.0001),t=Math.max(tYears,1/365),s=Math.max(spot,.0001),k=Math.max(strike,.0001),d1=(Math.log(s/k)+(rate+v*v/2)*t)/(v*Math.sqrt(t)),d2=d1-v*Math.sqrt(t),disc=Math.exp(-rate*t),price=type==="call"?s*cdf(d1)-k*disc*cdf(d2):k*disc*cdf(-d2)-s*cdf(-d1),delta=type==="call"?cdf(d1):cdf(d1)-1,gamma=Math.exp(-d1*d1/2)/(s*v*Math.sqrt(2*Math.PI*t)),vega=s*Math.exp(-d1*d1/2)/Math.sqrt(2*Math.PI)*Math.sqrt(t),theta=-(s*Math.exp(-d1*d1/2)*v/(2*Math.sqrt(2*Math.PI*t)))-(type==="call"?rate*k*disc*cdf(d2):-rate*k*disc*cdf(-d2));return{price,delta,gamma,vega:vega/100,theta:theta/365}}
export function optionPayoff(legs:OptionLeg[],spot:number){return legs.reduce((sum,l)=>{const intrinsic=l.type==="call"?Math.max(spot-l.strike,0):Math.max(l.strike-spot,0);return sum+(l.side==="buy"?1:-1)*(intrinsic-l.premium)*l.quantity},0)}
export function portfolioRisk(positions:{symbol:string;qty:number;entry:number;last:number}[],capital:number){const value=positions.reduce((s,p)=>s+p.qty*p.last,0),exposure=capital?value/capital*100:0,concentration=positions.map(p=>({symbol:p.symbol,weight:value?p.qty*p.last/value:0})).sort((a,b)=>b.weight-a.weight);return{value,exposure,concentration,largestWeight:(concentration[0]?.weight??0)*100}}
export function rankSignals(rows:{symbol:string;factors:FactorVector;change:number}[]){return[...rows].sort((a,b)=>b.factors.composite-a.factors.composite).map((x,i)=>({...x,rank:i+1}))}
