"use client";
import {useEffect,useMemo,useState} from "react";
import {blackScholes,factorScore,monteCarlo,portfolioRisk,riskMetrics,optionPayoff,rankSignals} from "../lib/advanced/terminal-engine";

type Candle={time:number;open:number;high:number;low:number;close:number;volume:number};
type Position={symbol:string;qty:number;entry:number;last:number};
const universe=["AAPL","MSFT","NVDA","AMZN","GOOGL","META","TSLA","JPM","RELIANCE.NS","TCS.NS","INFY.NS","GC=F"];
const fmt=(n:number|null|undefined)=>n==null||!Number.isFinite(n)?"—":n.toLocaleString(undefined,{maximumFractionDigits:2});

export default function AdvancedTerminal({symbol}:{symbol:string}){
 const [tab,setTab]=useState("SCREENER"); const [candles,setCandles]=useState<Candle[]>([]); const [quote,setQuote]=useState<any>(null); const [positions,setPositions]=useState<Position[]>([]); const [capital,setCapital]=useState(100000); const [riskPct,setRiskPct]=useState(1); const [stop,setStop]=useState(5); const [alert,setAlert]=useState(""); const [alerts,setAlerts]=useState<string[]>([]); const [journal,setJournal]=useState<{symbol:string;side:string;thesis:string;date:string}[]>([]);
 useEffect(()=>{Promise.all([fetch(`/api/market/history?symbol=${encodeURIComponent(symbol)}&range=1y&interval=1d`).then(r=>r.json()),fetch(`/api/market/quote?symbol=${encodeURIComponent(symbol)}`).then(r=>r.json())]).then(([h,q])=>{setCandles(h.data?.candles??[]);setQuote(q.data??q);}).catch(()=>{});},[symbol]);
 useEffect(()=>{try{setPositions(JSON.parse(localStorage.getItem("tb-positions")||"[]"));setAlerts(JSON.parse(localStorage.getItem("tb-alerts")||"[]"));setJournal(JSON.parse(localStorage.getItem("tb-journal")||"[]"));}catch{}} ,[]);
 const closes=useMemo(()=>candles.map(c=>c.close).filter(Number.isFinite),[candles]); const volumes=useMemo(()=>candles.map(c=>c.volume),[candles]);
 const factors=useMemo(()=>factorScore(closes,volumes),[closes,volumes]); const risk=useMemo(()=>riskMetrics(closes,capital,riskPct,stop),[closes,capital,riskPct,stop]); const mc=useMemo(()=>monteCarlo(closes,600,30),[closes]); const pr=useMemo(()=>portfolioRisk(positions,capital),[positions,capital]);
 const addAlert=()=>{if(!alert)return;const next=[...alerts,alert].slice(-25);setAlerts(next);localStorage.setItem("tb-alerts",JSON.stringify(next));setAlert("");};
 const addJournal=()=>{const next=[...journal,{symbol,side:quote?.price?"RESEARCH":"WAIT",thesis:`Composite factor ${fmt(factors.composite)}; 30-day Monte Carlo median ${fmt(mc.p50)}.`,date:new Date().toISOString()}].slice(-100);setJournal(next);localStorage.setItem("tb-journal",JSON.stringify(next));};
 const addPosition=()=>{const p={symbol,qty:1,entry:quote?.price??0,last:quote?.price??0};const next=[...positions,p];setPositions(next);localStorage.setItem("tb-positions",JSON.stringify(next));};
 const tabs=["SCREENER","FACTORS","RISK","PORTFOLIO","OPTIONS","BACKTEST","PAPER","ALERTS","JOURNAL","MACRO","AI LAB","PLUGINS"];
 return <section className="mt-4 rounded border border-[#1b2532] bg-[#0c1118] p-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs font-bold tracking-[.16em] text-[#5eead4]">ADVANCED RESEARCH & EXECUTION LAB</div><div className="mt-1 text-lg font-semibold">Quant workspace · {symbol}</div></div><div className="text-[10px] text-[#7f8da1]">NO BROKER ORDER ROUTING · RESEARCH / SIMULATION MODE</div></div>
  <div className="mt-4 flex gap-1 overflow-x-auto pb-2">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`whitespace-nowrap rounded border px-3 py-2 text-[10px] font-bold tracking-wider ${tab===t?"border-[#5eead4] bg-[#112322] text-[#5eead4]":"border-[#1b2532] text-[#7f8da1]"}`}>{t}</button>)}</div>
  {tab==="SCREENER"&&<Screener symbol={symbol} closes={closes} />}
  {tab==="FACTORS"&&<div className="grid gap-3 md:grid-cols-5">{Object.entries(factors).map(([k,v])=><Metric key={k} label={k.toUpperCase()} value={fmt(v as number)}/>)}</div>}
  {tab==="RISK"&&<div><div className="grid gap-3 md:grid-cols-4">{[["ANN VOL",risk.volatility],["VaR 95%",risk.var95],["CVaR 95%",risk.cvar95],["MAX DD",risk.maxDrawdown],["SHARPE",risk.sharpe],["RISK / TRADE",risk.riskPerTrade],["POSITION SIZE",risk.positionSize]].map(([k,v])=><Metric key={String(k)} label={String(k)} value={fmt(Number(v))}/>)}</div><div className="mt-4 grid gap-3 md:grid-cols-3"><label className="text-xs text-[#7f8da1]">Capital<input className="mt-1 w-full rounded border border-[#1b2532] bg-[#101722] p-2 text-sm" type="number" value={capital} onChange={e=>setCapital(+e.target.value)}/></label><label className="text-xs text-[#7f8da1]">Risk %<input className="mt-1 w-full rounded border border-[#1b2532] bg-[#101722] p-2 text-sm" type="number" step=".1" value={riskPct} onChange={e=>setRiskPct(+e.target.value)}/></label><label className="text-xs text-[#7f8da1]">Stop distance<input className="mt-1 w-full rounded border border-[#1b2532] bg-[#101722] p-2 text-sm" type="number" value={stop} onChange={e=>setStop(+e.target.value)}/></label></div></div>}
  {tab==="PORTFOLIO"&&<div><div className="grid gap-3 md:grid-cols-4"><Metric label="PORTFOLIO VALUE" value={fmt(pr.value)}/><Metric label="EXPOSURE %" value={fmt(pr.exposure)}/><Metric label="LARGEST WEIGHT %" value={fmt(pr.largestWeight)}/><Metric label="POSITIONS" value={String(positions.length)}/></div><button onClick={addPosition} className="mt-4 rounded bg-[#5eead4] px-3 py-2 text-xs font-bold text-[#07100f]">ADD {symbol} TO PAPER PORTFOLIO</button><div className="mt-3 space-y-2">{positions.map((p,i)=><div key={i} className="flex justify-between rounded border border-[#1b2532] p-3 text-xs"><span>{p.symbol}</span><span>{p.qty} × {fmt(p.last)}</span></div>)}</div></div>}
  {tab==="OPTIONS"&&<Options spot={quote?.price??100}/>} 
  {tab==="BACKTEST"&&<div><div className="grid gap-3 md:grid-cols-3"><Metric label="30D MC P05" value={fmt(mc.p05)}/><Metric label="30D MC MEDIAN" value={fmt(mc.p50)}/><Metric label="30D MC P95" value={fmt(mc.p95)}/></div><p className="mt-3 text-xs leading-5 text-[#7f8da1]">Monte Carlo resamples the observed daily-return distribution into 600 paths. Use the existing strategy backtest above for historical rule performance; this lab adds distributional robustness rather than pretending simulation is a forecast.</p></div>}
  {tab==="PAPER"&&<div className="grid gap-3 md:grid-cols-3"><Metric label="SIM CAPITAL" value={fmt(capital)}/><Metric label="RISK BUDGET" value={fmt(risk.riskPerTrade)}/><Metric label="SUGGESTED UNITS" value={fmt(risk.positionSize)}/><button onClick={addPosition} className="rounded border border-[#5eead4] p-3 text-xs text-[#5eead4]">SIMULATE ENTRY</button><button onClick={addJournal} className="rounded border border-[#1b2532] p-3 text-xs">LOG TRADE THESIS</button></div>}
  {tab==="ALERTS"&&<div><div className="flex gap-2"><input value={alert} onChange={e=>setAlert(e.target.value)} placeholder="AAPL price > 250 | RSI < 30 | custom rule" className="flex-1 rounded border border-[#1b2532] bg-[#101722] p-2 text-xs"/><button onClick={addAlert} className="rounded bg-[#5eead4] px-3 text-xs font-bold text-[#07100f]">SAVE</button></div><div className="mt-3 space-y-2">{alerts.map((a,i)=><div key={i} className="rounded border border-[#1b2532] p-3 text-xs">{a}</div>)}</div></div>}
  {tab==="JOURNAL"&&<div className="space-y-2">{journal.length?journal.map((j,i)=><div key={i} className="rounded border border-[#1b2532] p-3 text-xs"><b>{j.symbol}</b> · {j.side} · {new Date(j.date).toLocaleString()}<div className="mt-1 text-[#7f8da1]">{j.thesis}</div></div>):<div className="text-xs text-[#7f8da1]">No journal entries. Use LOG TRADE THESIS in Paper.</div>}</div>}
  {tab==="MACRO"&&<Macro />}
  {tab==="AI LAB"&&<AiLab symbol={symbol} factors={factors} risk={risk} mc={mc}/>} 
  {tab==="PLUGINS"&&<Plugins/>}
 </section>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded border border-[#1b2532] bg-[#101722] p-3"><div className="text-[9px] tracking-widest text-[#7f8da1]">{label}</div><div className="mt-1 font-mono text-lg">{value}</div></div>}
function Screener({symbol,closes}:{symbol:string;closes:number[]}){const [rows,setRows]=useState<any[]>([]);useEffect(()=>{Promise.all(universe.map(async s=>{try{const j=await fetch(`/api/market/history?symbol=${encodeURIComponent(s)}&range=3mo&interval=1d`).then(r=>r.json());const c=(j.data?.candles??[]).map((x:Candle)=>x.close);const q=await fetch(`/api/market/quote?symbol=${encodeURIComponent(s)}`).then(r=>r.json());return {symbol:s,change:q.data?.changePercent??0,factors:factorScore(c)};}catch{return {symbol:s,change:0,factors:factorScore([])}}})).then(x=>setRows(rankSignals(x)));},[]);return <div><div className="mb-3 text-xs text-[#7f8da1]">Cross-sectional Value / Momentum / Quality / Low-Vol composite. Selected: {symbol}</div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="text-[#7f8da1]"><th className="p-2">RANK</th><th>SYMBOL</th><th>CHANGE</th><th>VALUE</th><th>MOMENTUM</th><th>QUALITY</th><th>LOW VOL</th><th>COMPOSITE</th></tr></thead><tbody>{rows.map(r=><tr key={r.symbol} className="border-t border-[#1b2532]"><td className="p-2">#{r.rank}</td><td>{r.symbol}</td><td>{fmt(r.change)}%</td><td>{fmt(r.factors.value)}</td><td>{fmt(r.factors.momentum)}</td><td>{fmt(r.factors.quality)}</td><td>{fmt(r.factors.volatility)}</td><td className="font-bold text-[#5eead4]">{fmt(r.factors.composite)}</td></tr>)}</tbody></table></div></div>}
function Options({spot}:{spot:number}){const [strike,setStrike]=useState(Math.round(spot));const [vol,setVol]=useState(.3);const [days,setDays]=useState(30);const [rate,setRate]=useState(.06);const [type,setType]=useState<"call"|"put">("call");const [side,setSide]=useState<"buy"|"sell">("buy");const bs=blackScholes(type,spot,strike,days/365,rate,vol);const pnl=optionPayoff([{type,side,strike,premium:bs.price,quantity:1}],spot);return <div className="grid gap-4 md:grid-cols-2"><div className="space-y-3">{[["Strike",strike,setStrike],["IV",vol,setVol],["Days",days,setDays],["Rate",rate,setRate]].map(([k,v,set]:any)=><label key={String(k)} className="block text-xs text-[#7f8da1]">{k}<input className="mt-1 w-full rounded border border-[#1b2532] bg-[#101722] p-2" type="number" step={k==="IV"||k==="Rate"?".01":"1"} value={v} onChange={e=>set(+e.target.value)}/></label>)}<div className="flex gap-2"><select value={type} onChange={e=>setType(e.target.value as any)} className="rounded bg-[#101722] p-2 text-xs"><option>call</option><option>put</option></select><select value={side} onChange={e=>setSide(e.target.value as any)} className="rounded bg-[#101722] p-2 text-xs"><option>buy</option><option>sell</option></select></div></div><div className="grid gap-3 md:grid-cols-2">{[["MODEL PRICE",bs.price],["DELTA",bs.delta],["GAMMA",bs.gamma],["VEGA",bs.vega],["THETA / DAY",bs.theta],["CURRENT PAYOFF",pnl]].map(([k,v])=><Metric key={String(k)} label={String(k)} value={fmt(Number(v))}/>)}</div></div>}
function Macro(){return <div className="grid gap-3 md:grid-cols-4">{[["REGIME","Risk-aware"],["RATES","Monitor yield curve"],["INFLATION","Track CPI/PCE"],["LIQUIDITY","Track central-bank balance sheets"]].map(([k,v])=><div key={k} className="rounded border border-[#1b2532] p-4"><div className="text-[9px] tracking-widest text-[#7f8da1]">{k}</div><div className="mt-2 text-sm">{v}</div></div>)}</div>}
function AiLab({symbol,factors,risk,mc}:{symbol:string;factors:any;risk:any;mc:any}){const agents=[['TECHNICAL',factors.momentum>=50?'Trend evidence positive':'Trend evidence weak'],['RISK',risk.maxDrawdown<20?'Drawdown contained in sample':'Drawdown elevated in sample'],['QUANT',mc.p50>(mc.p05+mc.p95)/2?'Positive skew':'Neutral/negative skew'],['FUNDAMENTAL','Requires live provider fundamentals']];return <div><div className="grid gap-3 md:grid-cols-2">{agents.map(([a,t])=><div key={a} className="rounded border border-[#1b2532] p-4"><div className="text-[9px] tracking-widest text-[#5eead4]">{a} AGENT</div><div className="mt-2 text-sm">{t}</div></div>)}</div><div className="mt-4 rounded border border-[#23413d] bg-[#0c1516] p-4 text-xs leading-6"><b>RESEARCH SYNTHESIS · {symbol}</b><br/>Evidence should be triangulated across trend, valuation, catalysts, factor regime and portfolio risk. This panel is deliberately read-only: it does not place orders or claim certainty.</div></div>}
function Plugins(){return <div className="grid gap-3 md:grid-cols-3">{['Data Provider Registry','Strategy Adapter SDK','Research Report Exporter','Alert Adapter','Broker Adapter (paper-only)','MCP / Agent Tools'].map(x=><div key={x} className="rounded border border-[#1b2532] p-4"><div className="text-sm">{x}</div><div className="mt-2 text-[10px] text-[#7f8da1]">Extension point registered for provider/strategy integration.</div></div>)}</div>}
