"use client";
import {useState} from "react";
import MarketDataPanel from "./market-data-panel";
import MarketSearch from "./market-search";
import ProfessionalChart from "./professional-chart";
import TechnicalAnalysisPanel from "./technical-analysis-panel";
import TechnicalIndicatorsPanel from "./technical-indicators-panel";
import WatchlistPanel from "./watchlist-panel";
import IntelligencePanel from "./intelligence-panel";
import AdvancedTerminal from "./advanced-terminal";
import XauusdDecisionPanel from "./xauusd-decision-panel";
import AuthGate from "./auth-gate";
import TradingViewXauusdChart from "./tradingview-xauusd-chart";

const modules=[
 ["01","MARKET DATA","Multi-asset quotes, OHLCV, freshness, provider abstraction"],["02","SEARCH","Universal symbol/company/index discovery"],["03","CHARTS","Multi-timeframe professional chart workstation"],["04","TECHNICALS","Indicator stack, regime, momentum, volatility and structure"],["05","WATCHLISTS","Persistent lists with routing and live refresh"],["06","INTELLIGENCE","Fundamental + news + technical evidence + trade setup"],["07","SCREENER","Cross-sectional factor ranking and why-ranked signals"],["08","FUNDAMENTALS","Valuation, growth, quality and financial-statement adapters"],["09","NEWS / EVENTS","Catalysts, sentiment, earnings and macro-event workflow"],["10","F&O","Black-Scholes Greeks, payoff analysis and strategy-builder foundation"],["11","PORTFOLIO","Allocation, concentration, exposure and attribution foundation"],["12","RISK","VaR, CVaR, volatility, drawdown, Sharpe and position sizing"],["13","BACKTEST LAB","Historical strategy tests + Monte Carlo robustness"],["14","PAPER TRADING","Simulation ledger and risk-budgeted position sizing"],["15","ALERTS","Persistent rule definitions for price/indicator workflows"],["16","JOURNAL","Structured research/thesis log"],["17","MACRO","Macro regime/event integration surface"],["18","AI RESEARCH","Technical/risk/quant/fundamental analyst workflow"],["19","FACTOR LAB","Value, momentum, quality, low-vol composite research"],["20","PLUGIN PLATFORM","Provider, strategy, alert, report and agent extension points"],["21","PRODUCTION","Provider failover, validation, security and deployment gates"]
];
export default function Home(){const[selectedSymbol,setSelectedSymbol]=useState<string>();const activeSymbol=selectedSymbol??"XAUUSD";const[showMap,setShowMap]=useState(false);return <main className="min-h-screen p-4 md:p-6"><div className="mx-auto max-w-[1700px]">
<header className="mb-5 flex flex-wrap items-center gap-4 border-b border-[#1b2532] pb-4"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded bg-[#5eead4] text-sm font-black text-[#07100f]">TB</div><div><div className="text-sm font-bold tracking-[.18em]">TRADE BOX</div><div className="text-[11px] text-[#7f8da1]">ADVANCED FINANCIAL RESEARCH TERMINAL</div></div></div><MarketSearch onSelect={setSelectedSymbol}/><div className="rounded border border-[#23413d] bg-[#0c1516] px-3 py-2 text-xs text-[#5eead4]">QUANT / RESEARCH MODE</div></header>
<section className="grid gap-4 lg:grid-cols-[1.6fr_1fr]"><div className="rounded border border-[#1b2532] bg-[#0c1118] p-5"><div className="text-xs font-bold tracking-[.16em] text-[#5eead4]">INSTITUTIONAL-STYLE WORKFLOW</div><h1 className="mt-2 text-2xl font-semibold">One terminal for research, testing, risk and simulated execution.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#9aa8ba]">Trade Box now routes an instrument through market data, technicals, fundamentals, news, factor research, risk, backtesting, options analytics, portfolio simulation, alerts, journal and multi-agent research surfaces. Provider gaps are surfaced rather than hidden.</p><div className="mt-5 grid gap-2 sm:grid-cols-4">{[["EVIDENCE","Fundamental + technical + news"],["QUANT","Factors + backtest + Monte Carlo"],["RISK","VaR + CVaR + sizing + drawdown"],["EXECUTION","Paper ledger + alerts + journal"]].map(([a,b])=><div key={a} className="rounded border border-[#1b2532] bg-[#101722] p-3"><div className="text-[10px] tracking-widest text-[#7f8da1]">{a}</div><div className="mt-1 text-sm">{b}</div></div>)}</div></div><div className="rounded border border-[#1b2532] bg-[#0c1118] p-5"><div className="text-xs font-bold tracking-[.16em] text-[#5eead4]">CURRENT INSTRUMENT</div><div className="mt-3 font-mono text-2xl">{activeSymbol}</div><div className="mt-2 text-xs leading-5 text-[#7f8da1]">Change the symbol once; the chart, intelligence and advanced research lab follow it.</div><button onClick={()=>setShowMap(!showMap)} className="mt-5 rounded border border-[#1b2532] px-3 py-2 text-xs">{showMap?"HIDE SYSTEM MAP":"SHOW SYSTEM MAP"}</button></div></section>
<AuthGate><div className="mt-4"><>{activeSymbol === "XAUUSD" ? <TradingViewXauusdChart /> : <ProfessionalChart symbol={activeSymbol}/>} {activeSymbol === "XAUUSD" && <XauusdDecisionPanel/>}</><IntelligencePanel symbol={activeSymbol}/><AdvancedTerminal symbol={activeSymbol}/><TechnicalIndicatorsPanel symbol={activeSymbol}/><TechnicalAnalysisPanel symbol={activeSymbol}/><WatchlistPanel activeSymbol={activeSymbol} onSelect={setSelectedSymbol}/><MarketDataPanel requestedSymbol={selectedSymbol}/>
</div></AuthGate>{showMap&&<section className="mt-4 rounded border border-[#1b2532] bg-[#0c1118] p-5"><div className="mb-4 text-xs font-bold tracking-[.16em] text-[#5eead4]">SYSTEM MAP · PHASE 6 REMOVED</div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{modules.map(([n,t,d])=><div key={n} className="rounded border border-[#1b2532] bg-[#101722] p-4"><div className="text-[10px] font-bold tracking-[.18em] text-[#7f8da1]">{n}</div><div className="mt-2 font-medium">{t}</div><div className="mt-1 text-xs leading-5 text-[#7f8da1]">{d}</div></div>)}</div></section>}
<footer className="mt-5 flex flex-wrap justify-between gap-3 border-t border-[#1b2532] pt-4 text-[11px] text-[#617086]"><span>Trade Box · advanced research platform</span><span>Research and simulation only. Data availability and provider quality vary; no simulated result guarantees future performance.</span></footer></div></main>}
