import {config} from "./config";
import {calculateXauusdFeatures,type FeatureState} from "./features";
import {Mt5Bridge,type Mt5Account,type Mt5Position} from "./mt5";
export type Action="buy"|"sell"|"hold";
export interface Decision{action:Action;probabilities:{buy:number;sell:number;hold:number};reason:string}
export interface TraderSnapshot{timestamp:string;symbol:string;mode:"DRY_RUN"|"LIVE";price:{bid:number;ask:number;mid:number;spread:number};features:FeatureState;decision:Decision;risk:{allowed:boolean;reason:string};account?:Mt5Account;positions?:Mt5Position[];execution?:{success:boolean;side?:"buy"|"sell";volume?:number;price?:number;sl?:number;tp?:number;ticket?:number;error?:string}}
export async function jevDecision(f:FeatureState):Promise<Decision>{
 if(!config.jevApiKey)return mockDecision(f);
 const state={instrument:"XAUUSD",horizonMinutes:config.horizonMinutes,price:{bid:f.bid,ask:f.ask,mid:f.mid,spread:f.spread,spreadBps:f.spreadBps},returnsBps:f.returnsBps,technical:f.technical,market:f.market,volume:f.volume,recentPrices:f.recentPrices};
 const r=await fetch(config.jevEndpoint,{method:"POST",headers:{"Authorization":`Bearer ${config.jevApiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:config.jevModelId,state,questions:{direction:{type:"choice",instructions:"For XAUUSD, choose the strongest action over the configured horizon after considering spread, momentum, trend, RSI, EMAs, ATR, volume, session and volatility.",criteria:{buy:"XAUUSD is more likely to rise enough to justify a long entry after spread.",sell:"XAUUSD is more likely to fall enough to justify a short entry after spread.",hold:"Evidence is insufficient, conflicting, or the market is unattractive."}}}}),cache:"no-store"});
 const j:any=await r.json();if(!r.ok)throw new Error(j?.error?.message??"Jev API request failed");const a=j?.answers?.direction,pr=a?.probabilities??{},buy=Number(pr.buy??0),sell=Number(pr.sell??0),hold=Number(pr.hold??Math.max(0,1-Math.max(buy,sell))),action:Action=a?.choice==="buy"?"buy":a?.choice==="sell"?"sell":"hold";
 return {action,probabilities:{buy,sell,hold},reason:`Jev ${j?.model??config.jevModelId}: ${action}`};
}
function mockDecision(f:FeatureState):Decision{const trend=f.market.trend==="up"?.1:f.market.trend==="down"?-.1:0,momentum=Math.tanh(f.returnsBps.last15m/10)*.2,rsiSignal=f.technical.rsi14>70?-.08:f.technical.rsi14<30?.08:0,signal=trend+momentum+rsiSignal,buy=1/(1+Math.exp(-signal*4)),sell=1-buy,action:Action=buy>=config.minProbability&&buy-sell>=config.minProbabilityEdge?"buy":sell>=config.minProbability&&sell-buy>=config.minProbabilityEdge?"sell":"hold";return{action,probabilities:{buy,sell,hold:Math.max(0,1-Math.max(buy,sell))},reason:`trend=${f.market.trend}, RSI=${f.technical.rsi14.toFixed(1)}, 15m=${f.returnsBps.last15m.toFixed(2)}bps`}}
function riskCheck(f:FeatureState,d:Decision,a:Mt5Account,p:Mt5Position[]){if(d.action==="hold")return{allowed:false,reason:"HOLD signal"};if(f.spread/.01>config.maxSpreadPoints)return{allowed:false,reason:"Spread limit exceeded"};if(d.probabilities[d.action]<config.minProbability)return{allowed:false,reason:"Probability threshold not met"};if(Math.abs(d.probabilities.buy-d.probabilities.sell)<config.minProbabilityEdge)return{allowed:false,reason:"Probability edge not met"};if(a.profit<=-Math.abs(config.maxDailyLoss))return{allowed:false,reason:"Daily loss limit reached"};if(p.length>=config.maxPositions)return{allowed:false,reason:"Maximum positions reached"};if(p.reduce((s,x)=>s+x.volume,0)+config.lotSize>config.maxLots)return{allowed:false,reason:"Maximum lot exposure reached"};if(!f.technical.atr5m)return{allowed:false,reason:"ATR unavailable"};return{allowed:true,reason:"Risk checks passed"}}
export async function getXauusdSnapshot():Promise<TraderSnapshot>{const b=new Mt5Bridge();const[t,c,a,p]=await Promise.all([b.getTick(),b.getCandles(),b.getAccount(),b.getPositions()]);const f=calculateXauusdFeatures(c.candles,t),d=config.model==="jev"?await jevDecision(f):mockDecision(f),risk=riskCheck(f,d,a,p.positions);let execution:TraderSnapshot["execution"];if(risk.allowed){const side=d.action as "buy"|"sell",entry=side==="buy"?t.ask:t.bid,atr=f.technical.atr5m,sl=Number((side==="buy"?entry-atr*config.stopLossAtr:entry+atr*config.stopLossAtr).toFixed(2)),tp=Number((side==="buy"?entry+atr*config.takeProfitAtr:entry-atr*config.takeProfitAtr).toFixed(2));if(config.dryRun)execution={success:true,side,volume:config.lotSize,price:entry,sl,tp};else{const x=await b.order({symbol:config.symbol,side,volume:config.lotSize,sl,tp,deviation:20,comment:"Jev XAUUSD standalone"});execution={success:x.success,side,volume:x.volume??config.lotSize,price:x.price??entry,sl,tp,ticket:x.order??x.deal,error:x.error}}}return{timestamp:new Date().toISOString(),symbol:config.symbol,mode:config.dryRun?"DRY_RUN":"LIVE",price:{bid:t.bid,ask:t.ask,mid:(t.bid+t.ask)/2,spread:t.ask-t.bid},features:f,decision:d,risk,account:a,positions:p.positions,execution}}
